//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.StockBroker {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockBroker.IStockBrokerOps")]
    public interface IStockBrokerOps {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IStockBrokerOps/ReportNewStock")]
        void ReportNewStock(Stock stock);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockBrokerOpsChannel : Server.StockBroker.IStockBrokerOps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockBrokerOpsClient : System.ServiceModel.ClientBase<Server.StockBroker.IStockBrokerOps>, Server.StockBroker.IStockBrokerOps {
        
        public StockBrokerOpsClient() {
        }
        
        public StockBrokerOpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockBrokerOpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockBrokerOpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockBrokerOpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ReportNewStock(Stock stock) {
            base.Channel.ReportNewStock(stock);
        }
    }
}
