//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServerOps {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerOps.IServerOps")]
    public interface IServerOps {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerOps/DoWork", ReplyAction="http://tempuri.org/IServerOps/DoWorkResponse")]
        int DoWork(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerOps/GetEmail", ReplyAction="http://tempuri.org/IServerOps/GetEmailResponse")]
        string GetEmail(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerOps/AddStock", ReplyAction="http://tempuri.org/IServerOps/AddStockResponse")]
        string AddStock(Stock stock);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerOpsChannel : Client.ServerOps.IServerOps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerOpsClient : System.ServiceModel.ClientBase<Client.ServerOps.IServerOps>, Client.ServerOps.IServerOps {
        
        public ServerOpsClient() {
        }
        
        public ServerOpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerOpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerOpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerOpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DoWork(int num) {
            return base.Channel.DoWork(num);
        }
        
        public string GetEmail(int id) {
            return base.Channel.GetEmail(id);
        }
        
        public string AddStock(Stock stock) {
            return base.Channel.AddStock(stock);
        }
    }
}
